### ISSUE TITLE
simple Error Handling

### ISSUE THREAD

**Issue by mfleschutz** [ampl/amplpy#13]
It would be very helpful to have an example that demonstrates in a simple way, how to be able to debug a .mod-file.  At the moment I don't know how to set up the error handler right.

**Comment by fdabrandao** [comment]
Examples dedicated to ErrorHandler's and OutputHandler's are planned but have not been added yet. Here is some information that may help you meanwhile: 
- In [asyncexample.py ](https://github.com/ampl/amplpy/blob/master/examples/asyncexample.py) there is a simple error handler. 
- You can also see the implementation of the default error handler in [errorhandler.py](https://github.com/ampl/amplpy/blob/master/amplpy/errorhandler.py). 
- The documentation for AMPLException, which is passed as argument to ErrorHandler.error and ErrorHandler.warning is available at http://amplpy.readthedocs.io/en/latest/classes/amplexception.html; `AMPLException.getLineNumber()` may be what you are looking for.

Is this information helpful or did you have something else in mind for debugging mod files?

**Comment by mfleschutz** [comment]
Thank you for the quick answer. That probably helps.

Best regards,

Markus Fleschutz

Von: Filipe Brandao [mailto:notifications@github.com]
Gesendet: Freitag, 25. Mai 2018 02:49
An: ampl/amplpy <amplpy@noreply.github.com>
Cc: Markus Fleschutz <Markus.Fleschutz@hs-karlsruhe.de>; Author <author@noreply.github.com>
Betreff: Re: [ampl/amplpy] simple Error Handling (#13)


Examples dedicated to ErrorHandler's and OutputHandler's are planned but have not been added yet. Here is some information that may help you meanwhile:

  *   In asyncexample.py <https://github.com/ampl/amplpy/blob/master/examples/asyncexample.py> there is a simple error handler.
  *   You can also see the implementation of the default error handler in errorhandler.py<https://github.com/ampl/amplpy/blob/master/amplpy/errorhandler.py>.
  *   The documentation for AMPLException, which is passed as argument to ErrorHandler.error and ErrorHandler.warning is available at http://amplpy.readthedocs.io/en/latest/classes/amplexception.html; AMPLException.getLineNumber() may be what you are looking for.

Is this information helpful or did you have something else in mind for debugging mod files?

**Comment by mfleschutz** [comment]
It works. Is it also possible to get the syntax error messages like this:
```
	syntax error
context:   >>> set  <<< S default {1..8};
```

**Comment by fdabrandao** [comment]
Unfortunately that would require changes in the core API which may take a while to be made. Currently the only way to locate the error is by the line number or the offset. I opened a ticked for the internal API with this feature request.

**Comment by SteffenMeinecke** [comment]
Dear @fdabrandao,
thanks for all your developments! I have the same interest like @mfleschutz. Here is a example code snippet to demonstrate the current options:

```
import amplpy
ampl = amplpy.AMPL()
class MyErrorHandler(amplpy.ErrorHandler):
    def error(self, exception):
        print(f'AMPL Error, line {exception.getLineNumber()}, offset {exception.getOffset()}: {exception.getMessage()}')
ampl.setErrorHandler(MyErrorHandler())
ampl.eval("param b := 4;\nlet a := 3;")
```
prints `AMPL Error, line 2, offset 19: syntax error` and not
```
file_path, line 2 (offset 19):
        syntax error
context:  let  >>> a  <<< := 3;
```
as AMPL is printing.

**Comment by fdabrandao** [comment]
Hi @SteffenMeinecke,

Even though I forgot to comment here, context has been included in error messaged in `x-ampl` for some time and it has been included in the latest version of AMPL. Which version of AMPL do you have? Upgrading to the latest version of AMPL should fix the issue.

**Comment by SteffenMeinecke** [comment]
I was using amplpy 0.7.1 and AMPL Version 20221013. Since your message I updated to amplpy 0.8.6.
Could you please show how to extend above minimal example to print the context message in python?

**Comment by fdabrandao** [comment]
BTW: you can use amplpy modules to simplify the upgrade since AMPL and all solvers are now available as python modules: https://amplpy.readthedocs.io/en/latest/getting-started.html#amplpy-modules

In case you are using a time-limited bundle, you need to generate a new one.

**Comment by SteffenMeinecke** [comment]
Perfect, it works.
I think, this issue can be closed.

**Comment by fdabrandao** [comment]
Great! Over the next several months we will working substancially on the Python API so expect to see new features showing up soon and feel free to open issues for anything you think would be important to fix or improve.
