### ISSUE TITLE
use amplpy.dataframe.fromPandas with multidimensional dataframe 

### ISSUE THREAD

**Issue by mfleschutz** [ampl/amplpy#14]
I would like to set a multidimensional pandas-dataframe as data for ampl. Something like: 
```python3
from amplpy AMPL, DataFrame
ampl.eval("reset; Set T; Set S; param P {T,S};")
df = load_two_dimensional_pandas_dataframe()
adf = DataFrame.fromPandas(df)
ampl.setData(adf)
```
df looks like

```
        1    2    3
1     0.0  0.0  0.0
2     0.0  0.0  0.0
3     0.0  0.0  0.0
```
with the set S as columns and the set T as indices.

I get the error message:

```python
RuntimeError: file -
line 1 offset 30
1 is not a subscripted param
```

Is there an easy way to load multidimensional dataframe? Or do I have to do it according to dataframeexample.py?

**Comment by mfleschutz** [comment]
Thank you! That works.

**Comment by jennifer-dicarlo** [comment]
I'm getting the "not a subscripted param" message even though I am using DataFrames in tabular format....I was searching for the error and came across this thread.

As an example, ampl is rejecting this parameter which is indexed on F provided via the following pandas dataframe (and then converted to an amplpy dataframe):

```
      Vpf
F        
S1  50000
S3  50000
RH  50000
RY  50000
A   50000
RB  50000
O5  50000
O1  50000
RV  50000
O2  50000
```

Is there another reason for the "not a subscripted param" error message?

**Comment by fdabrandao** [comment]
Hi @jennifer-dicarlo,

Could you please share with us a small example where this happens?

The following code:
```python
import io
import pandas as pd
from amplpy import AMPL

data = io.StringIO('''F,Vpf
S1,50000
S3,50000
RH,50000
RY,50000
A,50000
RB,50000
O5,50000
O1,50000
RV,50000
O2,50000
''')
df_unindexed = pd.read_csv(data)
df = df_unindexed.set_index('F')

ampl = AMPL()
ampl.eval('''
set F;
param Vpf{F};
''')
ampl.setData(df, 'F')
ampl.display('Vpf')
```
produces the output:
```
Vpf [*] :=
 A  50000
O1  50000
O2  50000
O5  50000
RB  50000
RH  50000
RV  50000
RY  50000
S1  50000
S3  50000
;
```

**Comment by jennifer-dicarlo** [comment]
The problem is that I can't really come up with a small example....so many sets are built from other sets.  If I extract the information just to make Vpf the code is:

```
from amplpy import AMPL, DataFrame, Environment
import pandas as pd

ampl = AMPL(Environment('/Applications/AMPL'))
ampl.eval('reset;')

ampl.eval('''
set N;
set Fn {N} 	default {};
set FI default {};
set F= (union {n in N} Fn[n]) union FI;
param Vpf{F};
''')

def toAMPL(n):
    ampl.setData(DataFrame.fromPandas(n))

facs = ['S1','S3','RH','RY','A','RB','O5','O1','RV','O2']
nodes = facs +['CU1','CDN1','CDN2','CDN3','PB1','PB2']
Fnlist = [[x] for x in facs]
Fn = pd.Series(data=Fnlist, index=facs)
Fn.name = 'F'
Fn.index.name = 'N'

ampl.set['N'] = nodes
ampl.display('N')
for i,k in Fn.iteritems():
    ampl.set['Fn'][i] = k

ampl.display('F')

Vpfdata = [5000]*10
Vpf = pd.DataFrame(data=Vpfdata, index=facs, columns=['Vpf'])
Vpf.index.name = 'F'
toAMPL(Vpf)
ampl.display('Vpf')
ampl.close()
```
Which WORKS....but in the actual model does not....

I double checked that I didn't change any of the data types going in...for example:
From the small example:
```
In[13]: Vpf
Out[13]: 
     Vpf
F       
S1  5000
S3  5000
RH  5000
RY  5000
A   5000
RB  5000
O5  5000
O1  5000
RV  5000
O2  5000

In[14]: type(Vpf)
Out[14]: pandas.core.frame.DataFrame

In[15]: Vpf.dtypes
Out[15]: 
Vpf    int64
dtype: object
```

From the model:
```
In[16] PD['fpf']
Out[16]: 
      Vpf
F        
S1  50000
S3  50000
RH  50000
RY  50000
A   50000
RB  50000
O5  50000
O1  50000
RV  50000
O2  50000

In[17] type(PD['fpf'])
Out[17]: pandas.core.frame.DataFrame

In[18] PD['fpf'].dtypes
Out[18]: 
Vpf    int64
dtype: object

```

And I copied the declarations from the mod file too (attached...hopefully....had to make it a text file to upload).
[water_tc.txt](https://github.com/ampl/amplpy/files/6718199/water_tc.txt)

I typed in the data vs. reading it from Excel, but the data types are the same (strings, int).

**Comment by fdabrandao** [comment]
Hi @jennifer-dicarlo, I was able to run the code above with that part of the model and with the entire model (file test3.py attached) in the eval statement and both worked. Could you please add ampl._startRecording('session.log') right after instantiating the AMPL object and send us the file session.log so that we can see what happened that resulted in the error message?

**Comment by jennifer-dicarlo** [comment]
Sorry I have to post this here....I lost your email!

[session.log](https://github.com/ampl/amplpy/files/6718754/session.log)

I am not seeing an attachment on your last message, but I don't necessarily know what I am doing most of the time!  Haha!

**Comment by fdabrandao** [comment]
Hi @jennifer-dicarlo,

Sorry, the attachment got blocked due to the extension. Here is is now: [test3.py.txt](https://github.com/ampl/amplpy/files/6720354/test3.py.txt).

Regarding the session log, we see the following error after trying to assign data to Pk, which is not defined:

```
Pk is not defined.
Pk is not a subscripted param
```
