### ISSUE TITLE
Install error on MSYS2

### ISSUE THREAD

**Issue by wanakule** [ampl/amplpy#18]
The error was from installation on MSYS2 msys64/mingw64 for python-3.7 using:
python3 -m pip install amplpy

Here is the bottom part of error report:
    running build_ext
    building '_amplpython' extension
    creating build/temp.mingw-3.7
    creating build/temp.mingw-3.7/amplpy
    creating build/temp.mingw-3.7/amplpy/amplpython
    E:\msys64\mingw64\bin/x86_64-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DNDEBUG -Iamplpy/amplpython/include -IE:/msys64/mingw64/include/python3.7m -c amplpy/amplpython/amplpythonPYTHON_wrap.cxx -o build/temp.mingw-3.7/amplpy/amplpython/amplpythonPYTHON_wrap.o "/TP /EHsc"
    x86_64-w64-mingw32-gcc: error: /TP /EHsc: No such file or directory
    error: command 'E:\\msys64\\mingw64\\bin/x86_64-w64-mingw32-gcc.exe' failed with exit status 1

    ----------------------------------------
Command "E:/msys64/mingw64/bin/python3.exe -u -c "import setuptools, tokenize;__file__='C:/Users/WANAKU~1.VGR/AppData/Local/Temp/2/pip-install-7ppjur3l/amplpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:/Users/WANAKU~1.VGR/AppData/Local/Temp/2/pip-record-5aji3mot/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:/Users/WANAKU~1.VGR/AppData/Local/Temp/2/pip-install-7ppjur3l/amplpy/

**Comment by fdabrandao** [comment]
amplpy v0.7.0 has just been released and it can now be installed on MSYS2 and MINGW.
