### ISSUE TITLE
exportModel() exportData() treatment of sets

### ISSUE THREAD

**Issue by jlcox119** [ampl/amplpy#27]
Related to issue #7 but decided to open a new issue...

When sets are defined as

set NAME = 1..N; where N is some parameter

exportModel() and exportData() conspire to export a model and data files that AMPL will not accept. A simple model and data file demonstrating the issue are below.

The test is to load the original model and data files, then exportModel() and exportData(), then try to reload the exported model and data. This fails on the set SCRUBBERS, which is defined with a parameter (which is not yet defined) Nscrub in the exported model and then again in the data file. AMPL won't read the exported model and data files.

The goal is to read a baseline model and data file, make changes to the model and or data using the API, write out the model and data, and load these exported files into AMPL later (in a different environment) for solving.

# Original model:
model;

param Nscrub, >=0;

set SCRUBBERS = 1..Nscrub;

param cost {SCRUBBERS}, >= 0;
param pollutants {SCRUBBERS}, >= 0;
param MinPollutants, >=0;

var X {i in SCRUBBERS}, binary;

minimize Total_Cost: 
	sum {i in SCRUBBERS} cost[i] * X[i];

subject to Total_Pollutants: 
	sum {i in SCRUBBERS} pollutants[i] * X[i] >= MinPollutants;

# Original data:
data;

param Nscrub := 6;
param MinPollutants:= 60;

param:    cost pollutants:=
1         10   11
2         7    15
3         5    20
4         4    10
5         3    4
6         8    16;

# Exported model:
set SCRUBBERS = 1 .. Nscrub;
param Nscrub >= 0;
param cost{SCRUBBERS}  >= 0;
param pollutants{SCRUBBERS}  >= 0;
param MinPollutants >= 0;
var X{i in SCRUBBERS}  binary;
subject to Total_Pollutants: sum{i in SCRUBBERS} pollutants[i]*X[i] >=
  MinPollutants;
minimize Total_Cost: sum{i in SCRUBBERS} cost[i]*X[i];

# Exported data:
set SCRUBBERS := 1 2 3 4 5 6;
param MinPollutants = 60;
param Nscrub = 6;
param cost [*] :=
1  10
2   7
3   5
4   4
5   3
6   8
;
param pollutants [*] :=
1  11
2  15
3  20
4  10
5   4
6  16
;

**Comment by fdabrandao** [comment]
Thank you for reporting this issue. For the purpose you described there is a new command under development just to take a snapshot including the complete state of AMPL to load on another environment. Currently exportModel and exportData are workarounds that often require manual adjustments since they export the model separated from the data and as in your case it sometimes leads to redundant definitions.
