### ISSUE TITLE
fail to install amplpy with conda

### ISSUE THREAD

**Issue by salimoha** [ampl/amplpy#28]
I try to install amply with conda using:
'' conda install -c conda-forge amplpy ''

Then I get:
''
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - amplpy

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

''
Please advise.

**Comment by fdabrandao** [comment]
Hi @salimoha, 

We have just released version 0.6.11 with support to ppc64le. It will soon be available on conda, but you can try it now by building it locally as follows:
 ```
$ git clone https://github.com/ampl/amplpy.git
$ cd amplpy
$ python updatelib.py
$ python setup.py build
$ pip install . --upgrade
```
