### ISSUE TITLE
Run test cases for aarch64

### ISSUE THREAD

**Issue by odidev** [ampl/amplpy#34]
**Summary**
Running amplpy tests on aarch64.

**Problem description**
amplpy doesn't have test support for aarch64 due to missing aarch64 binary/zip here [(AMPL_URL)]( https://ampl.com/demo/) for running test cases. It would be really helpful if you suggest a way to validate if amplpy supports aarch64.

**Expected Output**
 Amplpy test cases should run successfully on aarch64. 

@amplpy-team, please let me know if I can help you adding test support for aarch64.

**Comment by fdabrandao** [comment]
Hi @odidev, amplpy v0.7.0 has just been released and it is now being build and tested for linux-aarch64 and linux-ppc64le too.
