### ISSUE TITLE
ampl.readData(filename): TypeError: basic_string

### ISSUE THREAD

**Issue by xrixhon** [ampl/amplpy#40]
Hello,

When I set up my ampl problem, I encounter an issue reading one specific file called "PESTD_data_decom_allowed.dat" (all the other files seem to be read flawlessly). Here is the error that comes out:

  File "/Users/xrixhon/.pyenv/versions/3.7.6/lib/python3.7/site-packages/amplpy/ampl.py", line 559, in readData
    self._impl.readData(filename)

TypeError: basic_string

I searched through the source code of amplpy but couldn't figure it out. Could you please help me?

To be exhaustive, here are the kind of lines written in the file:

let decom_allowed ['2015_2020' , '2010_2015' , 'NUCLEAR'] := 1;

Thanks in advance,

Best regards,

Xavier

**Comment by fdabrandao** [comment]
Hi Xavier,

That error comes for the underlying C++ API. Instead of ampl.readData(filename), could you please try ampl.readData(str(filename))?

Best regards,
Filipe

**Comment by fdabrandao** [comment]
Hi Xavier,

Sorry, I had not noticed the "let" in "let decom_allowed ['2015_2020' , '2010_2015' , 'NUCLEAR'] := 1;". "let" commands are part of models, not data. You can see the data format at https://ampl.com/BOOK/CHAPTERS/12-data.pdf. Instead of ampl.readData('PESTD_data_decom_allowed.dat'), could you please try ampl.read('PESTD_data_decom_allowed.dat')?

**Comment by xrixhon** [comment]
Hello Filipe,

Once again it is not the issue :s. Strangely, I've been able to run my code previously with a similar file but from now on, I've got this bug "out of nowhere"? Would you have any other idea to figure it out?

Thanks in advance for your quick response and your support,

Best regards,

Xavier

**Comment by fdabrandao** [comment]
Hi Xavier,

Could you please send all the files necessary to reproduce this issue to support@ampl.com?

 If that is not possible, you can add the following right after instantiating the AMPL object:
```python
ampl._startRecording('session.log')
ampl.setOption('_log_input_only', False)
```
This will produce a file `session.log` that should show what happened right before the exception was thrown.

**Comment by xrixhon** [comment]
Hello Filipe,

Thank you so much for your help. Generating the log helped to identify what was the issue. I was allocating the PESTD_data_decom_allowed.dat file before instantiating the parameter used in this file. It resulted in this no-clue-giving error TypeError: basic_string whereas the log file helped to identify the actual issue.

Thanks again for your help and your support,

Best regards,

Xavier
