### ISSUE TITLE
Warnings and Keyerror in ampl eval

### ISSUE THREAD

**Issue by Prashanthrajagopal91** [ampl/amplpy#51]
Hello,

I am trying to use the %%ampl_eval fn define my objectives and variables. But it seems like throwing a warning that its not defined. Note I have installed the recent one using 

!pip install "amplpy>=0.8.2b0" --upgrade --pre

<img width="941" alt="image" src="https://user-images.githubusercontent.com/102569937/230403226-78cb4556-a31e-443c-8b2c-cd5f2d4cb764.png">

Also there is a keyword error although my dataset contains the mentioned keywords,

<img width="941" alt="Screen Shot 2023-04-06 at 9 13 29 AM" src="https://user-images.githubusercontent.com/102569937/230404258-c128fe34-d6ca-4a9f-9c38-9a22a56f7c74.png">

Could you please help me understand this better? Thanks!

**Comment by fdabrandao** [comment]
Hi @Prashanthrajagopal91,

In that ampl_eval section you use `R_min`, `R_max`, etc. but I don't see their declarations. Are they declared somewhere else? They need to be declared before they are used as follows:

```
param R_min;
param R_max;
var R >= R_min, <= R_max;
```
