### ISSUE TITLE
Create a gurobipy.Model object from an AMPL object after data has been loaded

### ISSUE THREAD

**Issue by pjcpjc** [ampl/amplpy#9]
This is a great idea for so many reasons.

- You could then dump the .lp file (i.e. #8)
- You could then use `gurobipy.Model` for progress callbacks.
- You could use `amplpy` for the "heavy lifting" of building a "core model" and then use `gurobipy` to selectively edit that model for more specific sub-models. (I've used this pattern a couple of times, albeit with `gurobipy` exclusively).

That said, the current `ampl._exportGurobiModel` loses the variable and constraint names, and as a result it's hard to see how it could apply to any of these use cases.

So please do the following

- enable `_exportGurobiModel` to keep the variable and constraint names (either the only behavior or an optional behavior)
- change the name to `exportGurobiModel` (or something not starting with an underscore) and add a docstring.

**Comment by pjcpjc** [comment]
[sometimes_need_the_variables_and_constraint_names.ipynb.zip](https://github.com/ampl/amplpy/files/1949064/sometimes_need_the_variables_and_constraint_names.ipynb.zip)

**Comment by pjcpjc** [comment]
Alternately, you can just implement #8 directly, and so long as the .lp file (or .sav file or whatever file format) has the names, then you don't really need this. Whatever is easier.

**Comment by fdabrandao** [comment]
BTW, I use the underscore in the names of the methods like this one to indicate that they are for internal use only and that they are not officially part of the API so that people do not start using features that may be removed or renamed shortly after without being aware of that.

**Comment by fdabrandao** [comment]
`ampl.exportGurobiModel` now has no parameter (after 1d3e6bdaf26f1fe27356dff551f5670692974726). Ideally, it would be best to be able to load an NL file directly in gurobipy (it would be faster and more reliable). In case you know someone in charge of gurobipy that could add support to the NL format that would be great. Meanwhile, I think this method is ready to be used.

I am now considering adding a method to retrieve the solution from gurobipy and so that we can continue using amplpy after solving the model.

**Comment by pjcpjc** [comment]
I was thinking that you would retrieve the solution using the names (hence the name to maintain the names when you create the `gurobipy.Model`.

**Comment by pjcpjc** [comment]
Ready for testing - but reading the solution result is an open problem.

**Comment by pjcpjc** [comment]
Looks good, but we still need to figure out how to read the solution out if using `gurobipy.Model` because of its callbacks. Opening another issue for that.
